POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkxvdmVMYWNlMTgiLCJpZCI6IjY0NGQxOTg0NDBhZWEyMjEyMmRmYzBjZCIsImlhdCI6MTY4MzA1NTk5OCwiZXhwIjoxNjgzMDc3NTk4fQ.Z--fJIhlmk-QtaUkXZSl5JyR3e37jGxCDh7f1WwCEpU

{
    "title" :"HOHO",
    "author": "Joh3n",
    "url": "https://www.blogger.com/about/?bpli=1",
    "likes": 5
}